# Generated by Django 4.2.8 on 2023-12-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_comlited_todo_complited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='decription',
            new_name='description',
        ),
    ]
